version: '3.8'

services:
  ftp-server:
    container_name: my-ftp-server
    image: garethflowers/ftp-server
    environment:
      - PUBLIC_IP=192.168.1.211
      - FTP_USER=user
      - FTP_PASS=123
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp" # For passive mode
    volumes:
      - "/data:/home/orangepi/Documentos"

volumes:
  ftp_data: